name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_FLOWER_0E75C0700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/" 
          # 1. Change this to "out" (Next.js default export folder)
          output_location: "out" 
          # 2. Add this so Azure doesn't try to build it a second time
          skip_app_build: true
